### ISSUE TITLE
Time zone sensitive streaks

### ISSUE THREAD

**Issue by cocuriosa** [colegend/coapp#3]
**Issue**:
Right now the streaks of the different actions (habits, journal, focus, etc.) are resetting to the UTC time and not to the time zone the user has put as their settings. Also the check-boxes for the "next day" in the habit section appear at the UTC new day time and not at the user's time zone. 
The only thing that is working correctly with the user's time is the quotes - a new quote does appear at midnight of the user's set time. 

Expected behavior:
+ streaks resetting at midnight of the user's set time zone
+ new habit boxes appearing at midnight of the user's set time zone

**Comment by Eraldo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [habit streak timezones](https://trello.com/c/hmIJ11xX/166-habit-streak-timezones)
