### ISSUE TITLE
Wrong reward symbols in adventures

### ISSUE THREAD

**Issue by cocuriosa** [colegend/coapp#7]
# Bug Report

**coLegend Info**
Open your app and click on the 'co' logo in the main menu. Please share your version number which should appear on the 'coLegend' page. 

```
0.78.0
```

**Describe the Bug**
When I reviewed an adventure that is marked as belonging to the "Joy" life area I got an Academy coSymbol as reward. 

**Steps to Reproduce**
1. Go to '/project/fair/adventures'
2. Click on 'Smile :D'
3. Review it.
4. See error in reward screen: Academy coSymbol instead of Joy coSymbol 

**Expected Behavior**
As the adventure is marked as only Joy I expect to get a Joy coSymbol as a reward.

**Comment by Eraldo** [comment]
@cocuriosa thank you for capturing this issue. :smile: 
I was able to figure out what was going on.
The issue will be fixed in the next version.
